version: '3.7'
services:
  server:
    container_name: server
    build: ./server
    ports: 
      - '8000:8000'

  client: 
    container_name: client
    build: ./client
    ports: 
      - "8080:80"
    depends_on: 
      - server