# Generated by Django 4.2.9 on 2024-02-08 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vacation",
            name="actual_days",
        ),
        migrations.RemoveField(
            model_name="vacationbalance",
            name="actual_balance",
        ),
        migrations.AddField(
            model_name="vacationbalance",
            name="office_vacation_balance",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cshr.officevacationbalance",
            ),
        ),
    ]
