# Generated by Django 4.1 on 2022-08-11 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company_properties",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=45)),
                (
                    "image_of",
                    models.CharField(
                        blank=True,
                        max_length=140,
                        null=True
                        )),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="cshr.user"
                    ),
                ),
            ],
        ),
    ]
