# Generated by Django 4.2.9 on 2024-02-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0002_remove_vacation_actual_days_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vacationbalance",
            name="office_vacation_balance",
        ),
        migrations.AddField(
            model_name="vacation",
            name="actual_days",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="vacationbalance",
            name="actual_balance",
            field=models.JSONField(default=dict, null=True),
        ),
    ]
