# Generated by Django 4.1 on 2022-08-11 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0002_company_properties"),
        ("cshr", "0002_requests_compensation_hr_letters_vacation_and_more"),
    ]

    operations = []
