# Generated by Django 4.1 on 2022-08-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0004_evaluations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="MobileNumber",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="user",
            name="TelegramLink",
            field=models.CharField(max_length=100),
        ),
    ]
