# Generated by Django 4.2.9 on 2024-04-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0005_alter_user_social_insurance_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacation",
            name="end_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="vacation",
            name="from_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
