# Generated by Django 4.1 on 2022-08-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0007_user_image_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evaluations",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="office",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="requests",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="training_courses",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
