# Generated by Django 4.2.9 on 2024-04-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0008_alter_vacation_actual_days"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("Male", "male"), ("Female", "female")], max_length=30
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="team",
            field=models.CharField(
                choices=[
                    ("Business Development", "Businessdevelopment"),
                    ("Development", "Development"),
                    ("HR & Finance", "Hrandfinance"),
                    ("QA", "Qa"),
                    ("Marketing", "Marketing"),
                    ("Operations", "Operations"),
                    ("Support", "Support"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("Admin", "admin"),
                    ("User", "user"),
                    ("Supervisor", "supervisor"),
                ],
                max_length=30,
            ),
        ),
    ]
