# Generated by Django 4.1 on 2022-08-16 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0009_alter_user_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evaluations",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="office",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="requests",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="requests",
            name="status",
            field=models.CharField(
                choices=[
                    ("rejected", "Rejected"),
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="requests",
            name="type",
            field=models.CharField(
                choices=[
                    ("hr_letters", "HR Letters"),
                    ("compensation", "Compensation"),
                    ("vacations", "Vacations"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="training_courses",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(upload_to=""),
        ),
        migrations.AlterField(
            model_name="user",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cshr.office"
            ),
        ),
    ]
