# Generated by Django 4.2.13 on 2024-07-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0009_alter_user_gender_alter_user_team_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="team",
            field=models.CharField(
                choices=[
                    ("Business Development", "Businessdevelopment"),
                    ("Development", "Development"),
                    ("HR & Finance", "Hrandfinance"),
                    ("QA", "Qa"),
                    ("Marketing and Communications", "Marketingandcommunications"),
                    ("Operations", "Operations"),
                    ("Support", "Support"),
                ],
                max_length=30,
            ),
        ),
    ]
