# Generated by Django 4.2.13 on 2024-07-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0010_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="object_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="notification",
            name="object_type",
            field=models.CharField(
                choices=[("Vacation", "vacation")], default="Vacation", max_length=30
            ),
        ),
    ]
