# Generated by Django 4.1 on 2022-08-31 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0010_alter_evaluations_created_at_alter_office_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evaluations",
            name="user",
        ),
        migrations.AddField(
            model_name="evaluations",
            name="form",
            field=models.CharField(
                choices=[
                    ("Peer 2 Peer Form", "Peer 2 Peer Form"),
                    ("Reverse Form", "Reverse Form"),
                ],
                default="",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="evaluations",
            name="quarter",
            field=models.CharField(
                choices=[
                    ("Peer 2 Peer Form", "Peer 2 Peer Form"),
                    ("Reverse Form", "Reverse Form"),
                ],
                default="",
                max_length=150,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="company_properties",
            name="image_of",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="company_properties",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="UserEvaluations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "quarter",
                    models.CharField(
                        choices=[
                            ("Peer 2 Peer Form", "Peer 2 Peer Form"),
                            ("Reverse Form", "Reverse Form"),
                        ],
                        max_length=150,
                    ),
                ),
                ("link", models.CharField(max_length=150)),
                ("score", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
