# Generated by Django 4.1 on 2022-08-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0010_alter_evaluations_created_at_alter_office_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "get_latest_by": "created_at",
                "ordering": ["-first_name", "-last_name"],
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(upload_to="profile_image"),
        ),
    ]
