# Generated by Django 4.1 on 2022-08-24 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0010_alter_evaluations_created_at_alter_office_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company_properties",
            name="image_of",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="company_properties",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="requests",
            name="approval_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approve_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
