# Generated by Django 4.1 on 2022-08-29 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0010_alter_evaluations_created_at_alter_office_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="office",
            name="city",
            field=models.CharField(max_length=45),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="company_properties",
            name="image_of",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="company_properties",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="office",
            unique_together={("name", "country", "city")},
        ),
    ]
