# Generated by Django 4.1 on 2022-08-22 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0011_alter_user_options_alter_user_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="social_insurance_number",
            field=models.CharField(default="default", max_length=45),
            preserve_default=False,
        ),
    ]
