# Generated by Django 4.2.13 on 2024-07-08 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0012_remove_notification_object_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="receivers",
        ),
        migrations.AddField(
            model_name="notification",
            name="receiver",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_receiver",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
