# Generated by Django 4.1 on 2022-08-31 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0011_remove_evaluations_user_evaluations_form_and_more"),
        ("cshr", "0012_alter_user_location"),
    ]

    operations = []
