# Generated by Django 4.1 on 2022-08-22 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0012_user_reporting_to_user_social_insurance_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="reporting_to",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
