# Generated by Django 4.2.9 on 2024-07-09 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0010_alter_user_team"),
        ("cshr", "0013_remove_notification_receivers_notification_receiver"),
    ]

    operations = []
