# Generated by Django 4.1 on 2022-08-31 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0013_merge_20220831_1340"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="reporting_to",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
