# Generated by Django 4.1 on 2022-08-31 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0014_alter_user_reporting_to"),
    ]

    operations = [
        migrations.CreateModel(
            name="Meetings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("meeting_link", models.CharField(max_length=250)),
                ("date", models.DateTimeField()),
                (
                    "host_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="host_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invited_users",
                    models.ManyToManyField(
                        related_name="invited_users", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Meeting",
                "verbose_name_plural": "Meetings",
            },
        ),
    ]
