# Generated by Django 4.1 on 2022-09-01 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0014_alter_company_properties_image_of_and_more"),
        ("cshr", "0015_meetings"),
    ]

    operations = []
