# Generated by Django 4.2.13 on 2024-07-17 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0015_notification_request_status_alter_requests_status_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="notification",
            unique_together={("request_status", "request", "receiver", "sender")},
        ),
    ]
