# Generated by Django 4.1 on 2022-08-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0015_user_is_active_user_is_admin_user_is_staff_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user", name="birthday", field=models.DateField(null=True),
        ),
    ]
