# Generated by Django 4.1 on 2022-09-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0016_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="date",
            field=models.DateTimeField(null=True),
        ),
    ]
