# Generated by Django 4.1 on 2022-08-24 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0016_alter_user_birthday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="location",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="cshr.office"
            ),
        ),
    ]
