# Generated by Django 4.2.13 on 2024-08-28 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0016_alter_notification_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicholiday",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="office_holidays",
                to="cshr.office",
            ),
        ),
    ]
