# Generated by Django 4.1 on 2022-09-01 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0016_merge_20220901_1224"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.RenameField(
            model_name="user",
            old_name="userskills",
            new_name="skills",
        ),
        migrations.RemoveField(
            model_name="user",
            name="social_insurance_number",
        ),
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(upload_to=""),
        ),
        migrations.AlterField(
            model_name="user",
            name="reporting_to",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
