# Generated by Django 4.2.13 on 2024-10-20 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0017_alter_publicholiday_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_office",
                to="cshr.office",
            ),
        ),
    ]
