# Generated by Django 4.1 on 2022-09-05 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0017_rename_company_properties_companyproperties_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="skills",
        ),
        migrations.DeleteModel(
            name="Skills",
        ),
    ]
