# Generated by Django 4.1 on 2022-09-04 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0017_event_date"),
        ("cshr", "0017_rename_company_properties_companyproperties_and_more"),
    ]

    operations = []
