# Generated by Django 4.1 on 2022-08-29 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0012_alter_company_properties_image_of_and_more"),
        ("cshr", "0017_alter_user_location"),
    ]

    operations = []
