# Generated by Django 4.1 on 2022-08-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0017_alter_user_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserUserSkills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="userskills",
        ),
        migrations.DeleteModel(
            name="UserSkills",
        ),
        migrations.AddField(
            model_name="user",
            name="skills",
            field=models.ManyToManyField(
                related_name="skills", to="cshr.useruserskills"
            ),
        ),
    ]
