# Generated by Django 4.1 on 2022-09-05 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0018_merge_20220904_1937"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Training_Courses",
            new_name="TrainingCourses",
        ),
        migrations.RemoveField(
            model_name="hrletters",
            name="requests_ptr",
        ),
        migrations.RemoveField(
            model_name="vacation",
            name="requests_ptr",
        ),
        migrations.AlterField(
            model_name="requests",
            name="approval_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approve_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="Compensation",
        ),
        migrations.DeleteModel(
            name="HrLetters",
        ),
        migrations.DeleteModel(
            name="Vacation",
        ),
    ]
