# Generated by Django 4.1 on 2022-08-30 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0018_merge_20220825_1105"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HR_LETTERS",
            new_name="HrLetters",
        ),
    ]
