# Generated by Django 4.1 on 2022-08-30 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0019_rename_useruserskills_userskills"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company_properties",
            options={
                "verbose_name": "Company_property",
                "verbose_name_plural": "Company_properties",
            },
        ),
    ]
