# Generated by Django 4.1 on 2022-09-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0019_rename_company_properties_companyproperties_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                default="profile_image/default.png", upload_to="profile_image/"
            ),
        ),
    ]
