# Generated by Django 4.1 on 2022-08-31 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0019_alter_company_properties_image_of_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Company_properties",
            new_name="CompanyProperties",
        ),
    ]
