# Generated by Django 4.1 on 2022-09-05 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0019_rename_training_courses_trainingcourses_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Compensation",
            fields=[
                (
                    "requests_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="cshr.requests",
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=250)),
                ("from_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
            options={
                "abstract": False,
            },
            bases=("cshr.requests",),
        ),
        migrations.CreateModel(
            name="HrLetters",
            fields=[
                (
                    "requests_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="cshr.requests",
                    ),
                ),
                ("addresses", models.CharField(max_length=45)),
            ],
            options={
                "verbose_name": "Hr Letter",
                "verbose_name_plural": "Hr letters",
            },
            bases=("cshr.requests",),
        ),
        migrations.CreateModel(
            name="Vacation",
            fields=[
                (
                    "requests_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="cshr.requests",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("annual_leaves", "Annual Leaves"),
                            ("public_holidays", "Public Holidays"),
                            ("emergency_leave", "Emergency Leave"),
                            ("leave_excuses", "Leave Excuses"),
                        ],
                        default="annual_leaves",
                        max_length=20,
                    ),
                ),
                ("from_date", models.DateField()),
                ("end_date", models.DateField()),
                ("change_log", models.JSONField(default=list)),
            ],
            options={
                "abstract": False,
            },
            bases=("cshr.requests",),
        ),
    ]
