# Generated by Django 4.1 on 2022-08-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0020_alter_company_properties_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userskills",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
