# Generated by Django 4.1 on 2022-08-31 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0020_rename_company_properties_companyproperties"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Training_Courses",
            new_name="TrainingCourses",
        ),
    ]
