# Generated by Django 4.1 on 2022-09-05 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0021_alter_requests_approval_user"),
    ]

    operations = []
