# Generated by Django 4.1 on 2022-09-01 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0021_alter_userskills_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company_properties",
            options={
                "verbose_name": "Companyproperty",
                "verbose_name_plural": "Companyproperties",
            },
        ),
        migrations.AlterField(
            model_name="evaluations",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
