# Generated by Django 4.1 on 2022-09-01 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0022_alter_company_properties_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="reporting_to",
        ),
    ]
