# Generated by Django 4.1 on 2022-09-05 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0023_merge_20220905_1115"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userskills",
            options={},
        ),
    ]
