# Generated by Django 4.1 on 2022-09-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0024_alter_userskills_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="date",
            field=models.DateTimeField(null=True),
        ),
    ]
