# Generated by Django 4.0.7 on 2022-09-07 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0025_event_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="VacationBalance",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("sick_leaves", models.IntegerField(default=5)),
                ("compensation", models.IntegerField(default=0)),
                ("unpaid", models.IntegerField(default=0)),
                ("annual_leaves", models.IntegerField()),
                ("emergencies", models.IntegerField(default=5)),
                ("leave_execuses", models.IntegerField(default=4)),
                ("public_holidays", models.IntegerField()),
            ],
        ),
    ]
