# Generated by Django 4.0.7 on 2022-09-08 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cshr', '0025_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrletters',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
