# Generated by Django 4.0.7 on 2022-09-11 11:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cshr', '0025_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='reporting_to',
        ),
        migrations.AddField(
            model_name='user',
            name='reporting_to',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
