# Generated by Django 4.0.7 on 2022-09-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cshr', '0026_hrletters_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrletters',
            name='with_date',
            field=models.BooleanField(default=False),
        ),
    ]
