# Generated by Django 4.0.7 on 2022-09-08 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0026_vacationbalance"),
    ]

    operations = [
        migrations.CreateModel(
            name="VacationBalanceValues",
            fields=[
                (
                    "vacationbalance_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="cshr.vacationbalance",
                    ),
                ),
            ],
            bases=("cshr.vacationbalance",),
        ),
    ]
