# Generated by Django 4.0.7 on 2022-09-08 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0027_vacationbalancevalues"),
    ]

    operations = [
        migrations.DeleteModel(
            name="VacationBalanceValues",
        ),
    ]
