# Generated by Django 4.0.7 on 2022-09-08 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cshr', '0027_hrletters_with_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrletters',
            name='date',
            field=models.DateField(default=datetime.date(2022, 9, 8)),
        ),
    ]
