# Generated by Django 4.0.7 on 2022-09-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cshr', '0027_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(upload_to='profile_image/'),
        ),
    ]
