# Generated by Django 4.0.7 on 2022-09-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0028_delete_vacationbalancevalues"),
    ]

    operations = [
        migrations.CreateModel(
            name="VacationBalanceValues",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sick_leaves", models.IntegerField(default=100)),
                ("compensation", models.IntegerField(default=0)),
                ("unpaid", models.IntegerField(default=0)),
                ("annual_leaves", models.IntegerField(default=10)),
                ("emergency_leavess", models.IntegerField(default=5)),
                ("leave_execuses", models.IntegerField(default=4)),
                ("public_holidays", models.IntegerField(default=5)),
            ],
        ),
    ]
