# Generated by Django 4.0.7 on 2022-09-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0028_alter_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(null=True, blank=True, upload_to="profile_image/"),
        ),
    ]
