# Generated by Django 4.0.7 on 2022-09-11 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0029_alter_user_image"),
        ("cshr", "0031_publicholidays_alter_vacationbalance_compensation_and_more"),
    ]

    operations = []
