# Generated by Django 4.0.7 on 2022-09-13 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0027_alter_user_reporting_to"),
        ("cshr", "0031_publicholidays_alter_vacationbalance_compensation_and_more"),
    ]

    operations = []
