# Generated by Django 4.0.7 on 2022-09-11 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0032_merge_20220911_1303"),
    ]

    operations = [
        migrations.AddField(
            model_name="hrletters",
            name="date",
            field=models.DateField(default=datetime.date(2022, 9, 11)),
        ),
        migrations.AddField(
            model_name="hrletters",
            name="with_date",
            field=models.BooleanField(default=False),
        ),
    ]
