# Generated by Django 4.0.7 on 2022-09-11 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0032_delete_vacationbalance"),
    ]

    operations = [
        migrations.CreateModel(
            name="VacationBalance",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("sick_leaves", models.IntegerField()),
                ("compensation", models.IntegerField()),
                ("unpaid", models.IntegerField()),
                ("annual_leaves", models.IntegerField()),
                ("emergencies", models.IntegerField()),
                ("leave_execuses", models.IntegerField()),
                ("public_holidays", models.IntegerField()),
                ("date", models.DateField(auto_now=True)),
                ("old_balance", models.JSONField(default=dict, null=True)),
            ],
        ),
    ]
