# Generated by Django 4.0.7 on 2022-09-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0032_merge_20220911_1303"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetings",
            name="location",
            field=models.CharField(default="remote", max_length=250),
        ),
    ]
