# Generated by Django 4.0.7 on 2022-09-13 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cshr', '0032_merge_20220913_0759'),
        ('cshr', '0033_hrletters_date_hrletters_with_date'),
    ]

    operations = [
    ]
