# Generated by Django 4.0.7 on 2022-09-13 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cshr', '0034_merge_20220913_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrletters',
            name='date',
            field=models.DateField(default=datetime.date(2022, 9, 13)),
        ),
    ]
