# Generated by Django 4.0.7 on 2022-09-13 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0034_alter_event_options_rename_date_event_end_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="start_date",
            new_name="from_date",
        ),
    ]
