# Generated by Django 4.0.7 on 2022-09-14 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0035_rename_start_date_event_from_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={},
        ),
    ]
