# Generated by Django 4.0.7 on 2022-09-14 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0036_alter_event_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"verbose_name": "Event", "verbose_name_plural": "Events"},
        ),
    ]
