# Generated by Django 4.0.7 on 2022-09-15 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0032_merge_20220913_0759"),
        ("cshr", "0037_alter_event_options"),
    ]

    operations = []
