# Generated by Django 4.0.7 on 2022-09-14 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0035_alter_hrletters_date"),
        ("cshr", "0037_alter_event_options"),
    ]

    operations = []
