# Generated by Django 4.0.7 on 2022-09-14 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0038_merge_20220914_1120"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hrletters",
            name="date",
            field=models.DateField(default=datetime.date(2022, 9, 14)),
        ),
    ]
