# Generated by Django 4.0.7 on 2022-09-18 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0038_merge_20220918_0933"),
        ("cshr", "0040_user_address_user_job_title_alter_hrletters_date"),
    ]

    operations = []
