# Generated by Django 4.0.7 on 2022-09-18 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cshr', '0040_user_address_user_job_title_alter_hrletters_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrletters',
            name='date',
            field=models.DateField(default=datetime.date(2022, 9, 18)),
        ),
    ]
