# Generated by Django 4.0.7 on 2022-09-18 11:07

from django.db import migrations, models
import server.cshr.utils.generate


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0043_alter_hrletters_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="background_color",
            field=models.CharField(
                default=server.cshr.utils.generate.generate_random_color, max_length=10
            ),
        ),
    ]
