# Generated by Django 4.0.7 on 2022-09-19 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0041_alter_hrletters_date"),
        ("cshr", "0044_user_background_color_alter_user_image"),
    ]

    operations = []
