# Generated by Django 4.0.7 on 2022-09-19 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cshr', '0038_merge_20220915_1219'),
        ('cshr', '0044_user_background_color_alter_user_image'),
    ]

    operations = [
    ]
