# Generated by Django 4.0.7 on 2022-09-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0044_user_background_color_alter_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicholidays",
            name="date",
            field=models.DateField(unique=True),
        ),
    ]
