# Generated by Django 4.0.7 on 2022-09-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0045_merge_20220919_0851"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hrletters",
            name="date",
            field=models.DateField(auto_now=True),
        ),
    ]
