# Generated by Django 4.0.7 on 2022-09-19 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0045_alter_publicholidays_date"),
        ("cshr", "0046_alter_hrletters_date"),
    ]

    operations = []
