# Generated by Django 4.0.7 on 2022-09-21 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0047_merge_20220919_1044"),
        ("cshr", "0047_merge_20220919_1350"),
    ]

    operations = []
