# Generated by Django 4.0.7 on 2022-10-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0048_merge_20220921_1102"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vacationbalance",
            old_name="emergencies",
            new_name="emergency_leaves",
        ),
        migrations.AlterField(
            model_name="vacation",
            name="reason",
            field=models.CharField(
                choices=[
                    ("public_holidays", "Public Holidays"),
                    ("emergency_leaves", "Emergency Leave"),
                    ("annual_leaves", "Annual Leaves"),
                    ("leave_excuses", "Leave Excuses"),
                    ("sick_leaves", "Sick Leave"),
                    ("unpaid", "unpaid"),
                    ("compensation", "compensation"),
                ],
                default="annual_leaves",
                max_length=20,
            ),
        ),
        migrations.RemoveField(
            model_name="vacationbalance",
            name="public_holidays",
        ),
        migrations.AddField(
            model_name="vacationbalance",
            name="public_holidays",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
