# Generated by Django 4.0.7 on 2022-09-26 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cshr', '0048_merge_20220921_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacationbalance',
            name='public_holidays',
        ),
        migrations.AddField(
            model_name='vacationbalance',
            name='public_holidays',
            field=models.IntegerField(default=2),
        ),
    ]
