# Generated by Django 4.0.7 on 2022-10-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0049_rename_emergencies_vacationbalance_emergency_leaves_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evaluations",
            name="quarter",
            field=models.CharField(
                choices=[
                    ("1 : 3", "Jan March"),
                    ("4 : 6", "Apr Jun"),
                    ("7 : 9", "Jul Sep"),
                    ("10 : 12", "Oct Dec"),
                ],
                max_length=150,
            ),
        ),
        migrations.AlterField(
            model_name="userevaluations",
            name="quarter",
            field=models.CharField(
                choices=[
                    ("1 : 3", "Jan March"),
                    ("4 : 6", "Apr Jun"),
                    ("7 : 9", "Jul Sep"),
                    ("10 : 12", "Oct Dec"),
                ],
                max_length=150,
            ),
        ),
    ]
