# Generated by Django 4.0.7 on 2022-09-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0050_alter_vacationbalance_public_holidays"),
    ]

    operations = [
        migrations.AlterField(
            model_name="office",
            name="official_holidays",
            field=models.JSONField(default=list, null=True),
        ),
    ]
