# Generated by Django 4.0.7 on 2022-10-18 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0051_userdocements"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserDocements",
            new_name="UserDocuments",
        ),
    ]
