# Generated by Django 4.0.7 on 2022-10-12 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cshr', '0053_alter_vacation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacationbalance',
            name='emergency_leaves',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
