# Generated by Django 4.1.2 on 2022-10-22 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0054_office_weekend"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vacationbalance",
            old_name="leave_execuses",
            new_name="leave_excuses",
        ),
    ]
