# Generated by Django 4.0.7 on 2022-10-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cshr', '0054_vacationbalance_emergency_leaves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='status',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='Compensation',
        ),
    ]
