# Generated by Django 4.1.2 on 2022-10-22 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0055_rename_leave_execuses_vacationbalance_leave_excuses"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacation",
            name="taked_from_old_balance",
            field=models.BooleanField(default=False),
        ),
    ]
