# Generated by Django 4.1.2 on 2022-10-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0056_vacation_taked_from_old_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hrletters",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
