# Generated by Django 4.1.2 on 2022-10-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0058_rename_with_date_hrletters_with_salary_mentioned"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hrletters",
            old_name="date",
            new_name="end_date",
        ),
        migrations.AddField(
            model_name="hrletters",
            name="from_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
