# Generated by Django 4.1.2 on 2022-10-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0059_rename_date_hrletters_end_date_hrletters_from_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="hrletters",
            name="with_date",
            field=models.BooleanField(default=False),
        ),
    ]
