# Generated by Django 4.1.2 on 2022-10-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0062_offcialdocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="offcialdocument",
            name="type",
            field=models.CharField(
                choices=[
                    ("hr_letters", "HR Letters"),
                    ("compensations", "Compensations"),
                    ("vacations", "Vacations"),
                    ("official-document", "Official document"),
                ],
                default="official-document",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="requests",
            name="type",
            field=models.CharField(
                choices=[
                    ("hr_letters", "HR Letters"),
                    ("compensations", "Compensations"),
                    ("vacations", "Vacations"),
                    ("official-document", "Official document"),
                ],
                max_length=20,
            ),
        ),
    ]
