# Generated by Django 4.1.2 on 2022-10-23 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0064_rename_user_offcialdocument_applying_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="offcialdocument",
            name="approval_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="official_document_approval_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="offcialdocument",
            name="applying_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="official_document_applying_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
