# Generated by Django 4.1.2 on 2022-12-13 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0067_vacationbalance_actual_balance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offcialdocument",
            name="applying_user",
        ),
        migrations.RemoveField(
            model_name="offcialdocument",
            name="approval_user",
        ),
        migrations.RemoveField(
            model_name="offcialdocument",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="offcialdocument",
            name="id",
        ),
        migrations.RemoveField(
            model_name="offcialdocument",
            name="modified_at",
        ),
        migrations.RemoveField(
            model_name="offcialdocument",
            name="status",
        ),
        migrations.RemoveField(
            model_name="offcialdocument",
            name="type",
        ),
        migrations.AddField(
            model_name="offcialdocument",
            name="requests_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="cshr.requests",
            ),
            preserve_default=False,
        ),
    ]
