# Generated by Django 4.1.2 on 2023-10-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0068_remove_offcialdocument_applying_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="team",
            field=models.CharField(
                choices=[
                    ("Business Development", "Businessdevelopment"),
                    ("Development", "Development"),
                    ("HR & Finance", "Hrandfinance"),
                    ("QA", "Qa"),
                    ("Marketing", "Marketing"),
                    ("Operations", "Operations"),
                    ("Support", "Support"),
                ],
                max_length=20,
            ),
        ),
    ]
