# Generated by Django 4.1.2 on 2023-10-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0069_alter_user_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="office",
            name="weekend",
            field=models.CharField(
                choices=[
                    ("Friday:Saturday", "Friday:Saturday"),
                    ("Saturday:Sunday", "Saturday:Sunday"),
                ],
                default="Friday:Saturday",
                max_length=20,
            ),
        ),
    ]
