# Generated by Django 4.1.2 on 2023-11-01 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0071_publicholiday"),
    ]

    operations = [
        migrations.RenameField(
            model_name="publicholiday",
            old_name="date",
            new_name="holiday_date",
        ),
        migrations.AlterUniqueTogether(
            name="publicholiday",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="publicholiday",
            name="location",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="cshr.office",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="publicholiday",
            unique_together={("holiday_date", "location")},
        ),
        migrations.RemoveField(
            model_name="publicholiday",
            name="days",
        ),
    ]
