# Generated by Django 4.1.2 on 2023-11-05 07:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0073_alter_event_location_alter_event_people"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="people",
            field=models.ManyToManyField(
                related_name="event_participants", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
