# Generated by Django 4.1.2 on 2023-11-05 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0074_alter_event_people"),
    ]

    operations = [
        migrations.CreateModel(
            name="OfficeVacationBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("year", models.IntegerField()),
                ("annual_leaves", models.IntegerField(default=20)),
                ("sick_leaves", models.IntegerField(default=100)),
                ("compensation", models.IntegerField(default=100)),
                ("unpaid", models.IntegerField(default=100)),
                ("leave_excuses", models.IntegerField(default=6)),
                ("emergency_leaves", models.IntegerField(default=6)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cshr.office"
                    ),
                ),
                (
                    "public_holidays",
                    models.ManyToManyField(
                        related_name="public_holidays", to="cshr.publicholiday"
                    ),
                ),
            ],
            options={
                "unique_together": {("year", "location")},
            },
        ),
    ]
