# Generated by Django 4.1.2 on 2023-11-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0075_officevacationbalance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="officevacationbalance",
            name="year",
            field=models.IntegerField(default=2023),
        ),
    ]
