# Generated by Django 4.1.2 on 2023-11-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0076_alter_officevacationbalance_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicholiday",
            name="expired",
            field=models.BooleanField(default=False),
        ),
    ]
