# Generated by Django 4.1.2 on 2023-11-05 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0077_publicholiday_expired"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vacationbalance",
            name="public_holidays",
        ),
    ]
