# Generated by Django 4.1.2 on 2023-11-05 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0078_remove_vacationbalance_public_holidays"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="office",
            unique_together={("name", "country")},
        ),
    ]
