# Generated by Django 4.1.2 on 2023-11-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0079_alter_office_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="office",
            name="name",
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
