# Generated by Django 4.1.2 on 2023-11-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0080_alter_office_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="salary",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="skills",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="skills", to="cshr.userskills"
            ),
        ),
    ]
