# Generated by Django 4.1.2 on 2023-11-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0081_alter_user_salary_alter_user_skills"),
    ]

    operations = [
        migrations.AlterField(
            model_name="officevacationbalance",
            name="compensation",
            field=models.IntegerField(default=365),
        ),
        migrations.AlterField(
            model_name="officevacationbalance",
            name="sick_leaves",
            field=models.IntegerField(default=365),
        ),
        migrations.AlterField(
            model_name="officevacationbalance",
            name="unpaid",
            field=models.IntegerField(default=365),
        ),
    ]
