# Generated by Django 4.1.2 on 2023-11-28 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0082_alter_officevacationbalance_compensation_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vacation",
            name="taked_from_old_balance",
        ),
        migrations.RemoveField(
            model_name="vacationbalance",
            name="date",
        ),
        migrations.RemoveField(
            model_name="vacationbalance",
            name="old_balance",
        ),
    ]
