# Generated by Django 4.1.2 on 2023-12-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cshr", "0084_alter_user_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacation",
            name="actual_days",
            field=models.IntegerField(default=0),
        ),
    ]
