# name: Lint

# on:
#   push:
#     branches:
#       - '**' 

# jobs:
#   run-linters:
#     name: Run linters
#     runs-on: ubuntu-latest

#     steps:
#       - name: Check out Git repository
#         uses: actions/checkout@v2

#       - name: Set up Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: 3.8

#       - name: Install Python dependencies
#         run: pip install --upgrade flake8

#       - name: Run linters
#         uses: wearerequired/lint-action@v2
#         with:
#           flake8: true

#       - strategy:
#           matrix:
#             node-version: 18
#         steps:
#           - uses: actions/checkout@v2
#           - name: Use Node.js ${{ matrix.node-version }}
#             uses: actions/setup-node@v2
#             with:
#               cache: "pnpm"

#       - name: Install
#         run: pnpm

#       - name: Lint
#         run: |
#           pnpm lint
#           pnpm format

name: Lint

on:
  push:
    branches:
      - '**' 

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: pip install --upgrade flake8

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          flake8: true

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install
        run: pnpm

      - name: Lint and Format
        run: |
          pnpm lint
          pnpm format
