name: Test

on:
  push:
    branches: 
    - '**' 
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.8 ]
        node-version: [14.x]
        redis-version: [4]
    steps:
    - uses: actions/checkout@v3
    - name: Start Redis
      uses: supercharge/redis-github-action@1.4.0
      with:
        redis-version: ${{ matrix.redis-version }}
        redis-port: 6000
    - name: Create env file
      run: |
          touch .env
          echo DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }} >> .env
          echo DJANGO_DEBUG=${{ secrets.DJANGO_DEBUG }} >> .env
          echo EMAIL=${{ secrets.EMAIL }} >> .env
          echo EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }} >> .env
          echo EMAIL_HOST=${{ secrets.EMAIL_HOST }} >> .env
          echo REDIS_HOST=${{ secrets.REDIS_HOST }} >> .env
          echo REDIS_HOST_ONLY= localhost >> .env
          echo REDIS_PORT= 6000 >> .env
          cat .env
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: run celery
      run: |
          export DJANGO_SETTINGS_MODULE=server.settings
          poetry run celery -A server.cshr.celery.send_email worker --loglevel=DEBUG   
    - name: Run Tests
      run: |
        poetry run python manage.py test
